# Generated by Django 5.2.13 on 2026-05-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('user_tenant', models.CharField(max_length=100)),
                ('resource_tenant', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=200)),
                ('ip', models.GenericIPAddressField()),
                ('response_time_ms', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('user_tenant', models.CharField(max_length=100)),
                ('resource_tenant', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
